import { chromium } from '../frontend/node_modules/@playwright/test/index.mjs'

const browser = await chromium.launch({headless:true, executablePath:'/usr/bin/chromium', args:['--no-sandbox']})
const errors=[]
const desktop=await browser.newPage({viewport:{width:1584,height:950},deviceScaleFactor:1})
desktop.on('console',message=>{if(message.type()==='error') errors.push(message.text())})
desktop.on('pageerror',error=>errors.push(error.message))
await desktop.goto('http://127.0.0.1:20810/#asr',{waitUntil:'networkidle'})
await desktop.getByText('音频转写',{exact:true}).waitFor()
await desktop.waitForTimeout(400)
await desktop.screenshot({path:'/tmp/sandevistan-asr.png',fullPage:true})
await desktop.getByText('语音合成',{exact:true}).first().click()
await desktop.getByText('生成语音',{exact:false}).waitFor()
await desktop.waitForTimeout(400)
await desktop.screenshot({path:'/tmp/sandevistan-tts.png',fullPage:true})
await desktop.getByText('任务记录',{exact:true}).click()
await desktop.getByText('任务记录',{exact:true}).last().waitFor()
await desktop.waitForTimeout(400)
await desktop.screenshot({path:'/tmp/sandevistan-jobs.png',fullPage:true})
await desktop.getByText('系统状态',{exact:true}).click()
await desktop.getByText('模型状态',{exact:true}).waitFor()
await desktop.waitForTimeout(400)
await desktop.screenshot({path:'/tmp/sandevistan-system.png',fullPage:true})

const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1})
mobile.on('console',message=>{if(message.type()==='error') errors.push(message.text())})
await mobile.goto('http://127.0.0.1:20810/#asr',{waitUntil:'networkidle'})
await mobile.getByText('音频转写',{exact:true}).waitFor()
await mobile.waitForTimeout(400)
await mobile.screenshot({path:'/tmp/sandevistan-mobile-asr.png',fullPage:true})
await mobile.goto('http://127.0.0.1:20810/#tts',{waitUntil:'networkidle'})
await mobile.getByText('生成语音',{exact:false}).waitFor()
await mobile.waitForTimeout(400)
await mobile.screenshot({path:'/tmp/sandevistan-mobile-tts.png',fullPage:true})
console.log(JSON.stringify({title:await desktop.title(),desktopUrl:desktop.url(),mobileWidth:await mobile.evaluate(()=>document.documentElement.scrollWidth),errors},null,2))
await browser.close()
